In [2]:
def gauss_jordan_inverse(A):
    """Calcula la inversa de una matriz cuadrada A usando el método de Gauss-Jordan."""
    import numpy as np

    n = len(A)
    A = np.array(A, dtype=float)
    I = np.eye(n, dtype=float)
    
    for i in range(n):
        if A[i, i] == 0:
            for k in range(i + 1, n):
                if A[k, i] != 0:
                    A[[i, k]] = A[[k, i]]
                    I[[i, k]] = I[[k, i]]
                    break
            else:
                raise ValueError("La matriz no es invertible (pivote cero sin alternativas).")

        pivot = A[i, i]
        A[i] = A[i] / pivot
        I[i] = I[i] / pivot

        for j in range(n):
            if j != i:
                factor = A[j, i]
                A[j] = A[j] - factor * A[i]
                I[j] = I[j] - factor * I[i]

    return I

In [5]:
A = [[2, -3], [-1, 1]]
invA = gauss_jordan_inverse(A)
print("Inversa de A:")
print(invA)

Inversa de A:
[[-1. -3.]
 [-1. -2.]]


In [6]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
invA = gauss_jordan_inverse(A)
print("Inversa de A:")
print(invA)

Inversa de A:
[[-36.  45.  60. -80.]
 [  3.  -4.  -5.   7.]
 [  9. -11. -15.  20.]
 [ 29. -36. -48.  64.]]
